### ISSUE TITLE
Looping over roles

### ISSUE THREAD

**Issue by tupperward** [karroffel/datcord_bot#22]
I adapted a lot of your method for the rewrite branch in order to go through and add roles for preferred pronouns on my server. I retained looping through the server roles so that I can add the role without hardcoding a bunch of ids.

`@bot.command()
async def callme (ctx, newRole):
    user = ctx.message.author
    roles = ctx.guild.roles 
    rolesListAdd = []

    for userRole in user.roles:
        rolesListAdd.append(userRole.name.lower())

    if newRole in rolesListAdd:
        await ctx.send('You already have this role.')
            
    if newRole not in rolesListAdd:
        for role in roles:
            if role.name.lower() == newRole.lower():
                roleToAdd = role
        await user.add_roles(roleToAdd)
        await ctx.send('Role has been added')`

**Comment by Calinou** [comment]
Pronoun roles were added in https://github.com/Calinou/datcord_bot/commit/1fc292f705e48464e10914e8c60983601d04484f, closing. See #22 for possible code refactoring and cleanups.
