### ISSUE TITLE
Update discordpy to a supported version

### ISSUE THREAD

**Issue by Calinou** [karroffel/datcord_bot#24]
datcord_bot has been stuck on an old discordpy version for years. It would be nice to upgrade it to the latest version, so that the bot can run with Python 3.7 and later.

**Comment by winston-yallow** [comment]
I would be interested to work on this.

If I am not mistaken I will need to register my own bot to get a token for testing. Which permissions do I have to give to that test bot?

**Comment by Calinou** [comment]
@winston-yallow You need to give it the following permissions:

- Manage Roles
- Read Text Channels & See Voice Channels
- Send Messages
- Embed Links

**Comment by winston-yallow** [comment]
Got a working dev env, thanks! There are a few things that changed in discord.py between 0.16 and 1.2 so I need to adjust them. I will work more on this tomorrow.
