### ISSUE TITLE
Add new commands

### ISSUE THREAD

**Issue by karroffel** [karroffel/datcord_bot#8]
`!build`: `https://bintray.com/calinou/godot/editor/_latestVersion#files`

`!code`:
```

    \`\`\`swift
    func discord_highlight():
       if(using.backticks):
          "get colors"
    \`\`\`

    ```swift
    func discord_highlight():
       if(using.backticks):
          "get colors"
    ```

    \`or use inline highlighting\`
    `or use inline highlighting`

```

**Comment by Calinou** [comment]
These have been implemented in some way in https://github.com/Calinou/datcord_bot/commit/027a3e2ebd3f227e578e30701c63dc08765cd473, closing.
